version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.5
      - test-3.4
      - test-2.7
jobs:
  test-3.6: &test-template
    docker:
      - image: circleci/python:3.6.6

    working_directory: ~/rox-python

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            virtualenv venv-rox
            . venv-rox/bin/activate
            pip install -r requirements.txt
            pip install mock

      - save_cache:
          paths:
            - ./venv-rox
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv-rox/bin/activate
            echo $(python --version)
            python -m unittest discover --start-directory tests --top-level-directory .
  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5.5
  test-3.4:
    <<: *test-template
    docker:
      - image: circleci/python:3.4.8
  test-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7.15
